### ISSUE TITLE
File upload fail because not recognize file content type

### ISSUE THREAD

**Issue by semal** [RTIInternational/SMART#14]
![image](https://user-images.githubusercontent.com/5009351/60944162-a0935c80-a31a-11e9-992c-b9192e160724.png)
Always got this error message even using the example file.

**Comment by wengerm50** [comment]
The application uses the file's content type to determine how to process the file.  Your file has a content type of `application/octet-stream` which is "an arbitrary string of bytes".  Since that content type does not match any the application supports, it does not know how to process it.

What sort of file is that (csv, tsv, excel)?  If you add the file extension I think the application _may_  be able to process it then?

**Comment by rchew** [comment]
Going to close for now @semal -- let us know if you're still having an issue and we can re-open
