### ISSUE TITLE
'SMART' Equivalent for image datasets

### ISSUE THREAD

**Issue by namangt68** [RTIInternational/SMART#6]
Thanks for this useful tool. I know that this is not the right place to ask but is there any 'SMART' equivalent for image datasets.
Something that allow parallel annotation efforts and monitoring and open source also.

**Comment by rchew** [comment]
Thanks for the kind words!

To my knowledge, I'm not aware of an any application for annotating images that also does parallel annotation, monitoring, and is also open source (that doesn't mean it doesn't exist -- it's more likely due to my ignorance).

Personally, I've used [RectLabel](https://rectlabel.com/) before and can vouch for it being useful for labeling images on OS X.  It's not open source, but it does have a free version which you can download from the Mac App Store.  For a commercial PaaS with the mentioned capabilities, I've heard great things about [LabelBox](https://www.labelbox.com/).

I hope this helps -- if you do run into any good alternatives, let me know!
